// Code generated by goctl. DO NOT EDIT.
package types

type UserPermIdsReq struct {
	AppCode     string `form:"appCode"`
	RequestTime int64  `form:"requestTime"`
	Sign        string `form:"sign"`
	Uid         int64  `form:"uid"`
	PermType    string `form:"permType,optional"`
}

type UserPermIdsResp struct {
	List []int64 `json:"list"`
}

type UserPermKeysReq struct {
	AppCode     string `form:"appCode"`
	RequestTime int64  `form:"requestTime"`
	Sign        string `form:"sign"`
	Uid         int64  `form:"uid"`
	PermType    string `form:"permType,optional"`
}

type UserPermKeysResp struct {
	List []string `json:"list"`
}

type UserGroupsReq struct {
	AppCode     string `form:"appCode"`
	RequestTime int64  `form:"requestTime"`
	Sign        string `form:"sign"`
	Uid         int64  `form:"uid"`
}

type UserGroupsResp struct {
	List []string `json:"list"`
}

type UserGroupReq struct {
	AppCode     string `json:"appCode"`
	RequestTime int64  `json:"requestTime"`
	Sign        string `json:"sign"`
	Uid         int64  `json:"uid"`
	GroupId     int64  `json:"groupId"`
}

type UserGroupResp struct {
}

type UserRoleReq struct {
	AppCode     string `json:"appCode"`
	RequestTime int64  `json:"requestTime"`
	Sign        string `json:"sign"`
	Uid         int64  `json:"uid"`
	RoleId      int64  `json:"roleId"`
}

type UserRoleResp struct {
}

type PermItem struct {
	Id         int64  `json:"id"`
	Type       string `json:"type"`
	Key        string `json:"key"`
	Name       string `json:"name"`
	Desc       string `json:"desc"`
	CreateTime string `json:"create_time"`
	UpdateTime string `json:"update_time"`
}

type PermListReq struct {
	AppCode     string `form:"appCode"`
	RequestTime int64  `form:"requestTime"`
	Sign        string `form:"sign"`
}

type PermListResp struct {
	List []PermItem `json:"list"`
}

type PermRecord struct {
	Type string `json:"type"`
	Key  string `json:"key"`
	Name string `json:"name"`
	Desc string `json:"desc"`
}

type AddPermBatchReq struct {
	AppCode     string       `json:"appCode"`
	RequestTime int64        `json:"requestTime"`
	Sign        string       `json:"sign"`
	Permissions []PermRecord `json:"permissions"`
}

type AddPermBatchResp struct {
}

type DeletePermReq struct {
	AppCode     string `json:"appCode"`
	RequestTime int64  `json:"requestTime"`
	Sign        string `json:"sign"`
	Key         string `json:"key"`
}

type DeletePermResp struct {
}

type Role struct {
	Id         int64  `json:"id"`
	Name       string `json:"name"`
	Desc       string `json:"desc"`
	CreateTime string `json:"create_time"`
	UpdateTime string `json:"update_time"`
}

type RoleListReq struct {
	AppCode     string `form:"appCode"`
	RequestTime int64  `form:"requestTime"`
	Sign        string `form:"sign"`
}

type RoleListResp struct {
	List []Role `json:"list"`
}

type GetRoleByNameReq struct {
	AppCode     string `form:"appCode"`
	RequestTime int64  `form:"requestTime"`
	Sign        string `form:"sign"`
	RoleName    string `form:"roleName"`
}

type GetRoleByNameResp struct {
	List []Role `json:"list"`
}

type UpsertRoleReq struct {
	AppCode     string `json:"appCode"`
	RequestTime int64  `json:"requestTime"`
	Sign        string `json:"sign"`
	RoleName    string `json:"roleName"`
	RoleDesc    string `json:"roleDesc"`
}

type UpsertRoleResp struct {
	Role Role `json:"role"`
}

type UpdateRolePermReq struct {
	AppCode     string   `json:"appCode"`
	RequestTime int64    `json:"requestTime"`
	Sign        string   `json:"sign"`
	RoleName    string   `json:"roleName"`
	PermKeys    []string `json:"permissionKeys"`
}

type UpdateRolePermResp struct {
}

type Group struct {
	Id         int64  `json:"id"`
	Name       string `json:"name"`
	Desc       string `json:"desc"`
	CreateTime string `json:"create_time"`
	UpdateTime string `json:"update_time"`
}

type GroupListReq struct {
	AppCode     string `form:"appCode"`
	RequestTime int64  `form:"requestTime"`
	Sign        string `form:"sign"`
}

type GroupListResp struct {
	List []Group `json:"list"`
}

type GetGroupByNameReq struct {
	AppCode     string `form:"appCode"`
	RequestTime int64  `form:"requestTime"`
	Sign        string `form:"sign"`
	GroupName   string `form:"groupName"`
}

type GetGroupByNameResp struct {
	List []Group `json:"list"`
}

type UpsertGroupReq struct {
	AppCode     string `json:"appCode"`
	RequestTime int64  `json:"requestTime"`
	Sign        string `json:"sign"`
	GroupName   string `json:"groupName"`
	GroupDesc   string `json:"groupDesc"`
}

type UpsertGroupResp struct {
	Group Group `json:"group"`
}

type User struct {
	Uid      int64  `json:"uid"`
	Nickname string `json:"nickname"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
}

type GetUserByGroupNameReq struct {
	AppCode     string `form:"appCode"`
	RequestTime int64  `form:"requestTime"`
	Sign        string `form:"sign"`
	GroupName   string `form:"groupName"`
}

type GetUserByGroupNameResp struct {
	List []User `json:"list"`
}

type GroupPermIdsReq struct {
	AppCode     string `form:"appCode"`
	RequestTime int64  `form:"requestTime"`
	Sign        string `form:"sign"`
	GroupName   string `form:"groupName"`
}

type GroupPermIdsResp struct {
	List []int64 `json:"list"`
}

type GroupPermKeysReq struct {
	AppCode     string `form:"appCode"`
	RequestTime int64  `form:"requestTime"`
	Sign        string `form:"sign"`
	GroupName   string `form:"groupName"`
}

type GroupPermKeysResp struct {
	List []string `json:"list"`
}
