// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoReq struct {
}

type UserInfoResp struct {
	Uid         int64    `json:"uid"`
	Nickname    string   `json:"nickname"`
	Email       string   `json:"email"`
	Phone       string   `json:"phone"`
	Permissions []string `json:"permissions"`
}

type RegisterReq struct {
	Username    string `json:"username"`
	Password    string `json:"password"`
	DupPassword string `json:"dupPassword"`
}

type RegisterResp struct {
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken string `json:"accessToken"` // jwt token
}

type LogoutReq struct {
	Token string `json:"token"`
}

type LogoutResp struct {
}

type UserItem struct {
	Uid      int64   `json:"uid"`
	Nickname string  `json:"nickname"`
	Groups   []int64 `json:"groups"`
	Roles    []int64 `json:"roles"`
}

type UserPageListReq struct {
	Page     int64  `form:"page"`
	PageSize int64  `form:"pageSize"`
	ClientId int64  `form:"client_id"`
	GroupId  int64  `form:"group_id,optional"`
	RoleId   int64  `form:"role_id,optional"`
	Search   string `form:"search,optional"`
}

type UserPageListResp struct {
	Page     int64      `json:"page"`
	PageSize int64      `json:"pageSize"`
	Total    int64      `json:"total"`
	List     []UserItem `json:"list"`
}

type UpdateUserPermReq struct {
	Uid      int64   `path:"uid"`
	ClientId int64   `json:"client_id"`
	Groups   []int64 `json:"groups"`
	Roles    []int64 `json:"roles"`
}

type UpdateUserPermResp struct {
}

type ClientItem struct {
	Id         int64  `json:"id"`
	Name       string `json:"name"`
	AppCode    string `json:"app_code"`
	PrivateKey string `json:"private_key"`
	Department string `json:"department"`
	Maintainer string `json:"maintainer"`
	Status     int64  `json:"status"`
	Type       int64  `json:"type"`
	CreateTime string `json:"create_time"`
	UpdateTime string `json:"update_time"`
}

type ClientListReq struct {
}

type ClientListResp struct {
	List []ClientItem `json:"list"`
}

type AddClientReq struct {
	Name       string `json:"name"`
	AppCode    string `json:"app_code"`
	Department string `json:"department"`
	Maintainer string `json:"maintainer"`
}

type AddClientResp struct {
}

type UpdateClientReq struct {
	Id         int64  `path:"id"`
	Name       string `json:"name"`
	AppCode    string `json:"app_code"`
	Department string `json:"department"`
	Maintainer string `json:"maintainer"`
	Status     int64  `json:"status"`
}

type UpdateClientResp struct {
}

type DeleteClientReq struct {
	Id int64 `path:"id"`
}

type DeleteClientResp struct {
}

type GroupOption struct {
	Id       int64  `json:"id"`
	ClientId int64  `json:"client_id"`
	Name     string `json:"name"`
	Desc     string `json:"desc"`
}

type RoleOption struct {
	Id       int64  `json:"id"`
	ClientId int64  `json:"client_id"`
	Name     string `json:"name"`
	Desc     string `json:"desc"`
}

type PermOption struct {
	Id       int64  `json:"id"`
	ClientId int64  `json:"client_id"`
	Type     string `json:"type"`
	Key      string `json:"key"`
	Name     string `json:"name"`
	Desc     string `json:"desc"`
}

type ClientOption struct {
	Id        int64         `json:"id"`
	Name      string        `json:"name"`
	AppCode   string        `json:"app_code"`
	Groups    []GroupOption `json:"groups"`
	Roles     []RoleOption  `json:"roles"`
	Perms     []PermOption  `json:"perms"`
	PermTypes []string      `json:"permTypes"`
}

type ClientOptionsReq struct {
}

type ClientOptionsResp struct {
	List []ClientOption `json:"list"`
}

type PermItem struct {
	Id         int64  `json:"id"`
	ClientId   int64  `json:"client_id"`
	Type       string `json:"type"`
	Key        string `json:"key"`
	Name       string `json:"name"`
	Desc       string `json:"desc"`
	Editable   int64  `json:"editable"`
	CreateTime string `json:"create_time"`
	UpdateTime string `json:"update_time"`
}

type PermPageListReq struct {
	Page     int64  `form:"page"`
	PageSize int64  `form:"pageSize"`
	ClientId int64  `form:"client_id"`
	Type     string `form:"type,optional"`
	Editable string `form:"editable,optional"`
	Search   string `form:"search,optional"`
}

type PermPageListResp struct {
	Page     int64      `json:"page"`
	PageSize int64      `json:"pageSize"`
	Total    int64      `json:"total"`
	List     []PermItem `json:"list"`
}

type AddPermReq struct {
	ClientId int64  `json:"client_id"`
	Type     string `json:"type"`
	Key      string `json:"key"`
	Name     string `json:"name"`
	Desc     string `json:"desc"`
}

type AddPermResp struct {
}

type UpdatePermReq struct {
	Id       int64  `path:"id"`
	ClientId int64  `json:"client_id"`
	Type     string `json:"type"`
	Key      string `json:"key"`
	Name     string `json:"name"`
	Desc     string `json:"desc"`
}

type UpdatePermResp struct {
}

type DeletePermReq struct {
	Id int64 `path:"id"`
}

type DeletePermResp struct {
}

type Role struct {
	Id          int64    `json:"id"`
	ClientId    int64    `json:"client_id"`
	Name        string   `json:"name"`
	Desc        string   `json:"desc"`
	Editable    int64    `json:"editable"`
	CreateTime  string   `json:"create_time"`
	UpdateTime  string   `json:"update_time"`
	Permissions []string `json:"permissions"`
}

type RoleListReq struct {
	ClientId int64  `form:"client_id"`
	Editable string `form:"editable,optional"`
}

type RoleListResp struct {
	List []Role `json:"list"`
}

type AddRoleReq struct {
	ClientId    int64    `json:"client_id"`
	Name        string   `json:"name"`
	Desc        string   `json:"desc"`
	Permissions []string `json:"permissions"`
}

type AddRoleResp struct {
}

type UpdateRoleReq struct {
	Id          int64    `path:"id"`
	ClientId    int64    `json:"client_id"`
	Name        string   `json:"name"`
	Desc        string   `json:"desc"`
	Permissions []string `json:"permissions"`
}

type UpdateRoleResp struct {
}

type DeleteRoleReq struct {
	Id int64 `path:"id"`
}

type DeleteRoleResp struct {
}

type Group struct {
	Id         int64   `json:"id"`
	ClientId   int64   `json:"client_id"`
	Name       string  `json:"name"`
	Desc       string  `json:"desc"`
	Editable   int64   `json:"editable"`
	CreateTime string  `json:"create_time"`
	UpdateTime string  `json:"update_time"`
	Roles      []int64 `json:"roles"`
}

type GroupListReq struct {
	ClientId int64  `form:"client_id"`
	Editable string `form:"editable,optional"`
}

type GroupListResp struct {
	List []Group `json:"list"`
}

type AddGroupReq struct {
	ClientId int64   `json:"client_id"`
	Name     string  `json:"name"`
	Desc     string  `json:"desc"`
	Roles    []int64 `json:"roles"`
}

type AddGroupResp struct {
}

type UpdateGroupReq struct {
	Id       int64   `path:"id"`
	ClientId int64   `json:"client_id"`
	Name     string  `json:"name"`
	Desc     string  `json:"desc"`
	Roles    []int64 `json:"roles"`
}

type UpdateGroupResp struct {
}

type DeleteGroupReq struct {
	Id int64 `path:"id"`
}

type DeleteGroupResp struct {
}
